export interface CountryCode {
  code: string;
  flag: string;
  name: string;
}

export const countryCodes: CountryCode[] = [
  { name: 'Lebanon', flag: '🇱🇧', code: '+961' },
  { name: 'United Arab Emirates', flag: '🇦🇪', code: '+971' },
  { name: 'Saudi Arabia', flag: '🇸🇦', code: '+966' },
  { name: 'Jordan', flag: '🇯🇴', code: '+962' },
  { name: 'Egypt', flag: '🇪🇬', code: '+20' },
  { name: 'Iraq', flag: '🇮🇶', code: '+964' },
  { name: 'Oman', flag: '🇴🇲', code: '+968' },
  { name: 'Qatar', flag: '🇶🇦', code: '+974' },
  { name: 'Kuwait', flag: '🇰🇼', code: '+965' },
  { name: 'Bahrain', flag: '🇧🇭', code: '+973' },
  { name: 'Syria', flag: '🇸🇾', code: '+963' },
  { name: 'Palestine', flag: '🇵🇸', code: '+970' },
  { name: 'Yemen', flag: '🇾🇪', code: '+967' },
  { name: 'Morocco', flag: '🇲🇦', code: '+212' },
  { name: 'Algeria', flag: '🇩🇿', code: '+213' },
  { name: 'Tunisia', flag: '🇹🇳', code: '+216' },
  { name: 'Libya', flag: '🇱🇾', code: '+218' },
  { name: 'Sudan', flag: '🇸🇩', code: '+249' },
  { name: 'United States', flag: '🇺🇸', code: '+1' },
  { name: 'Canada', flag: '🇨🇦', code: '+1' },
  { name: 'United Kingdom', flag: '🇬🇧', code: '+44' },
  { name: 'France', flag: '🇫🇷', code: '+33' },
  { name: 'Germany', flag: '🇩🇪', code: '+49' },
  { name: 'Italy', flag: '🇮🇹', code: '+39' },
  { name: 'Spain', flag: '🇪🇸', code: '+34' },
  { name: 'Netherlands', flag: '🇳🇱', code: '+31' },
  { name: 'Belgium', flag: '🇧🇪', code: '+32' },
  { name: 'Switzerland', flag: '🇨🇭', code: '+41' },
  { name: 'Sweden', flag: '🇸🇪', code: '+46' },
  { name: 'Norway', flag: '🇳🇴', code: '+47' },
  { name: 'Denmark', flag: '🇩🇰', code: '+45' },
  { name: 'Finland', flag: '🇫🇮', code: '+358' },
  { name: 'Australia', flag: '🇦🇺', code: '+61' },
  { name: 'New Zealand', flag: '🇳🇿', code: '+64' },
  { name: 'Brazil', flag: '🇧🇷', code: '+55' },
  { name: 'Mexico', flag: '🇲🇽', code: '+52' },
  { name: 'Argentina', flag: '🇦🇷', code: '+54' },
  { name: 'Chile', flag: '🇨🇱', code: '+56' },
  { name: 'Colombia', flag: '🇨🇴', code: '+57' },
  { name: 'Peru', flag: '🇵🇪', code: '+51' },
  { name: 'Japan', flag: '🇯🇵', code: '+81' },
  { name: 'South Korea', flag: '🇰🇷', code: '+82' },
  { name: 'China', flag: '🇨🇳', code: '+86' },
  { name: 'India', flag: '🇮🇳', code: '+91' },
  { name: 'Pakistan', flag: '🇵🇰', code: '+92' },
  { name: 'Bangladesh', flag: '🇧🇩', code: '+880' },
  { name: 'Indonesia', flag: '🇮🇩', code: '+62' },
  { name: 'Malaysia', flag: '🇲🇾', code: '+60' },
  { name: 'Singapore', flag: '🇸🇬', code: '+65' },
  { name: 'Thailand', flag: '🇹🇭', code: '+66' },
  { name: 'Vietnam', flag: '🇻🇳', code: '+84' },
  { name: 'Philippines', flag: '🇵🇭', code: '+63' },
  { name: 'South Africa', flag: '🇿🇦', code: '+27' },
  { name: 'Nigeria', flag: '🇳🇬', code: '+234' },
  { name: 'Kenya', flag: '🇰🇪', code: '+254' },
  { name: 'Turkey', flag: '🇹🇷', code: '+90' },
  { name: 'Iran', flag: '🇮🇷', code: '+98' },
  { name: 'Russia', flag: '🇷🇺', code: '+7' },
  { name: 'Ukraine', flag: '🇺🇦', code: '+380' },
  { name: 'Poland', flag: '🇵🇱', code: '+48' },
  { name: 'Romania', flag: '🇷🇴', code: '+40' },
  { name: 'Greece', flag: '🇬🇷', code: '+30' },
  { name: 'Portugal', flag: '🇵🇹', code: '+351' },
  { name: 'Ireland', flag: '🇮🇪', code: '+353' },
  { name: 'Austria', flag: '🇦🇹', code: '+43' },
  { name: 'Czech Republic', flag: '🇨🇿', code: '+420' },
  { name: 'Hungary', flag: '🇭🇺', code: '+36' }
];
